-- =====================================================================
-- 07_seed_codes.sql   labels for the FARS codes this database accepts
-- Sources: FARS Analytical User's Manual (NHTSA, 2024, 2025) and the FARS/CRSS
-- Pedestrian Bicyclist Crash Typing Manual (NHTSA, 2022, 2025). None of these
-- lists changed between 2020 and 2024, so every row uses the default validity
-- years 2020-2024. Codes that mean "not a pedestrian" (PEDLOC 7, PEDPOS 77,
-- PEDCTYPE 0) are left out on purpose: this database holds pedestrians only.
--
-- Not seeded yet: BODY_TYP (about 70 labels). They come from NHTSA's format file
-- when the pipeline loads the vehicle rows. Until then the CHECK (1-99) guards
-- the column and v_ped_transactions groups the codes into vehicle classes.
-- =====================================================================

INSERT INTO code_lookup (variable, code, label, is_unknown) VALUES
  ('rur_urb', 1, 'Rural', false),
  ('rur_urb', 2, 'Urban', false),
  ('rur_urb', 6, 'Trafficway Not in State Inventory', true),
  ('rur_urb', 8, 'Not Reported', true),
  ('rur_urb', 9, 'Unknown', true),

  ('func_sys', 1, 'Interstate', false),
  ('func_sys', 2, 'Principal Arterial - Other Freeways and Expressways', false),
  ('func_sys', 3, 'Principal Arterial - Other', false),
  ('func_sys', 4, 'Minor Arterial', false),
  ('func_sys', 5, 'Major Collector', false),
  ('func_sys', 6, 'Minor Collector', false),
  ('func_sys', 7, 'Local', false),
  ('func_sys', 96, 'Trafficway Not in State Inventory', true),
  ('func_sys', 98, 'Not Reported', true),
  ('func_sys', 99, 'Unknown', true),

  ('reljct2', 1, 'Non-Junction', false),
  ('reljct2', 2, 'Intersection', false),
  ('reljct2', 3, 'Intersection-Related', false),
  ('reljct2', 4, 'Driveway Access', false),
  ('reljct2', 5, 'Entrance/Exit Ramp Related', false),
  ('reljct2', 6, 'Railway Grade Crossing', false),
  ('reljct2', 7, 'Crossover-Related', false),
  ('reljct2', 8, 'Driveway Access Related', false),
  ('reljct2', 16, 'Shared-Use Path Crossing', false),
  ('reljct2', 17, 'Acceleration/Deceleration Lane', false),
  ('reljct2', 18, 'Through Roadway', false),
  ('reljct2', 19, 'Other Location Within Interchange Area', false),
  ('reljct2', 20, 'Entrance/Exit Ramp', false),
  ('reljct2', 98, 'Not Reported', true),
  ('reljct2', 99, 'Reported as Unknown', true),

  ('lgt_cond', 1, 'Daylight', false),
  ('lgt_cond', 2, 'Dark - Not Lighted', false),
  ('lgt_cond', 3, 'Dark - Lighted', false),
  ('lgt_cond', 4, 'Dawn', false),
  ('lgt_cond', 5, 'Dusk', false),
  ('lgt_cond', 6, 'Dark - Unknown Lighting', false),
  ('lgt_cond', 7, 'Other', false),
  ('lgt_cond', 8, 'Not Reported', true),
  ('lgt_cond', 9, 'Reported as Unknown', true),

  ('weather', 1, 'Clear', false),
  ('weather', 2, 'Rain', false),
  ('weather', 3, 'Sleet or Hail', false),
  ('weather', 4, 'Snow', false),
  ('weather', 5, 'Fog, Smog, Smoke', false),
  ('weather', 6, 'Severe Crosswinds', false),
  ('weather', 7, 'Blowing Sand, Soil, Dirt', false),
  ('weather', 8, 'Other', false),
  ('weather', 10, 'Cloudy', false),
  ('weather', 11, 'Blowing Snow', false),
  ('weather', 12, 'Freezing Rain or Drizzle', false),
  ('weather', 98, 'Not Reported', true),
  ('weather', 99, 'Reported as Unknown', true),

  ('day_week', 1, 'Sunday', false),
  ('day_week', 2, 'Monday', false),
  ('day_week', 3, 'Tuesday', false),
  ('day_week', 4, 'Wednesday', false),
  ('day_week', 5, 'Thursday', false),
  ('day_week', 6, 'Friday', false),
  ('day_week', 7, 'Saturday', false),

  ('hour', 99, 'Unknown', true),

  ('vspd_lim', 0, 'No Statutory Limit/Non-Trafficway or Driveway Access', false),
  ('vspd_lim', 98, 'Not Reported', true),
  ('vspd_lim', 99, 'Reported as Unknown', true),

  ('hit_run', 0, 'No', false),
  ('hit_run', 1, 'Yes', false),
  ('hit_run', 9, 'Reported as Unknown', true),

  ('per_typ', 5, 'Pedestrian', false),
  ('inj_sev', 4, 'Fatal Injury (K)', false),

  ('age', 998, 'Not Reported', true),
  ('age', 999, 'Reported as Unknown', true),

  ('sex', 1, 'Male', false),
  ('sex', 2, 'Female', false),
  ('sex', 8, 'Not Reported', true),
  ('sex', 9, 'Reported as Unknown', true),

  ('drinking', 0, 'No (Alcohol Not Involved)', false),
  ('drinking', 1, 'Yes (Alcohol Involved)', false),
  ('drinking', 8, 'Not Reported', true),
  ('drinking', 9, 'Reported as Unknown', true),

  ('pbcwalk', 0, 'None Noted', false),
  ('pbcwalk', 1, 'Yes', false),
  ('pbcwalk', 9, 'Unknown', true),

  ('pbswalk', 0, 'None Noted', false),
  ('pbswalk', 1, 'Yes', false),
  ('pbswalk', 9, 'Unknown', true),

  ('pedloc', 1, 'At Intersection', false),
  ('pedloc', 2, 'Intersection-Related', false),
  ('pedloc', 3, 'Not At Intersection', false),
  ('pedloc', 4, 'Non-Trafficway Location', false),
  ('pedloc', 9, 'Unknown/Insufficient Information', true),

  ('pedpos', 1, 'Intersection Area', false),
  ('pedpos', 2, 'Crosswalk Area', false),
  ('pedpos', 3, 'Travel Lane', false),
  ('pedpos', 4, 'Paved Shoulder/Bicycle Lane/Parking Lane', false),
  ('pedpos', 5, 'Sidewalk/Shared-Use Path/Driveway Access', false),
  ('pedpos', 6, 'Unpaved Right-of-Way', false),
  ('pedpos', 7, 'Non-Trafficway - Driveway', false),
  ('pedpos', 8, 'Non-Trafficway - Parking Lot/Other', false),
  ('pedpos', 9, 'Other/Unknown', true);

-- PBCAT crash groups and the crash types that belong to each one
INSERT INTO pbcat_group (pedcgp, label) VALUES
  (100, 'Unusual Circumstances'),
  (200, 'Backing Vehicle'),
  (310, 'Working or Playing in Roadway'),
  (340, 'Bus Stop-Related'),
  (350, 'Unique Midblock'),
  (400, 'Walking/Running Along Roadway'),
  (460, 'Driveway Access/Driveway Access Related'),
  (500, 'Waiting to Cross'),
  (600, 'Pedestrian in Roadway - Circumstances Unknown'),
  (720, 'Multiple Threat/Trapped'),
  (740, 'Dash/Dart-Out'),
  (750, 'Crossing Roadway - Vehicle Not Turning'),
  (790, 'Crossing Roadway - Vehicle Turning'),
  (800, 'Non-Trafficway'),
  (910, 'Crossing Expressway'),
  (990, 'Other/Unknown - Insufficient Details');

INSERT INTO pbcat_type (pedctype, label, pedcgp) VALUES
  (120, 'Dispute-Related', 100),
  (130, 'Pedestrian on Vehicle', 100),
  (140, 'Vehicle Into Vehicle or Vehicle Into Object', 100),
  (150, 'Motor Vehicle Loss of Control', 100),
  (160, 'Pedestrian Loss of Control', 100),
  (190, 'Other Unusual Circumstances', 100),
  (220, 'Driverless Vehicle', 100),
  (230, 'Disabled Vehicle-Related', 100),
  (240, 'Emergency Vehicle-Related', 100),
  (250, 'Play Vehicle-Related', 100),
  (211, 'Backing Vehicle - Non-Trafficway - Driveway', 200),
  (212, 'Backing Vehicle - Driveway Access', 200),
  (213, 'Backing Vehicle - Trafficway', 200),
  (214, 'Backing Vehicle - Non-Trafficway - Parking Lot', 200),
  (219, 'Backing Vehicle - Other/Unknown', 200),
  (311, 'Working in Roadway', 310),
  (312, 'Playing in Roadway', 310),
  (341, 'Transit Bus Stop-Related', 340),
  (342, 'School Bus Stop-Related', 340),
  (320, 'Entering/Exiting Parked or Stopped Vehicle', 350),
  (330, 'Mailbox-Related', 350),
  (360, 'Ice Cream/Vendor Truck-Related', 350),
  (410, 'Walking/Running Along Roadway With Traffic - From Behind', 400),
  (420, 'Walking/Running Along Roadway With Traffic - From Front', 400),
  (430, 'Walking/Running Along Roadway Against Traffic - From Behind', 400),
  (440, 'Walking/Running Along Roadway Against Traffic - From Front', 400),
  (459, 'Walking/Running Along Roadway - Direction/Position Unknown', 400),
  (461, 'Motorist Entering Driveway', 460),
  (465, 'Motorist Exiting Driveway', 460),
  (469, 'Driveway Access - Other/Unknown', 460),
  (510, 'Waiting to Cross - Vehicle Turning', 500),
  (520, 'Waiting to Cross - Vehicle Not Turning', 500),
  (590, 'Waiting to Cross - Vehicle Action Unknown', 500),
  (313, 'Lying in Roadway', 600),
  (610, 'Standing in Roadway', 600),
  (620, 'Walking in Roadway', 600),
  (710, 'Multiple Threat', 720),
  (730, 'Trapped', 720),
  (741, 'Dash - Run, No Visual Obstruction Noted', 740),
  (742, 'Dart-Out - Visual Obstruction Noted', 740),
  (760, 'Pedestrian Failed to Yield', 750),
  (770, 'Motorist Failed to Yield', 750),
  (781, 'Motorist Left Turn - Parallel Paths', 790),
  (782, 'Motorist Left Turn - Perpendicular Paths', 790),
  (791, 'Motorist Right Turn - Parallel Paths', 790),
  (792, 'Motorist Right Turn on Red - Parallel Paths', 790),
  (794, 'Motorist Right Turn on Red - Perpendicular Paths', 790),
  (795, 'Motorist Right Turn - Perpendicular Paths', 790),
  (799, 'Motorist Turn/Merge - Other/Unknown', 790),
  (830, 'Non-Trafficway - Parking Lot', 800),
  (890, 'Non-Trafficway - Other/Unknown', 800),
  (910, 'Crossing an Expressway', 910),
  (680, 'Not At Intersection - Other/Unknown', 990),
  (690, 'At Intersection - Other/Unknown', 990),
  (900, 'Other - Unknown Location', 990);
